var patentinfo =[
{PatNumber: "9,450,865", Title: " Open shortest path first extensions↵        in su…ort of wavelength switched optical networks,↵    ", Date: "September 20, 2016"},
{PatNumber: "9,392,348", Title: " Path computation element↵        protocol (PCEP) …signment,↵        and impairment validation,↵    ", Date: "July 12, 2016"},
{PatNumber: "9,300,428", Title: " Extending routing↵        protocols to accommodate wavelength switched optical networks,↵    ", Date: "March 29, 2016"},
{PatNumber: "9,276,838", Title: " Software defined↵         network virtualization …specific topology abstraction and interface,↵    ", Date: "March 1, 2016"},
{PatNumber: "9,270,597", Title: " Representing↵         bandwidth constraints in partially controlled environments,↵    ", Date: "February 23, 2016"},
{PatNumber: "9,270,366", Title: " Impairment aware↵         path computation element method and system,↵    ", Date: "February 23, 2016"},
{PatNumber: "9,231,726", Title: " Extending path↵         computation element proto…velength↵         switched optical networks,↵    ", Date: "January 5, 2016"},
{PatNumber: "9,055,354", Title: "Method for generalized multi-protocol↵        labe…k↵        element compatibility constraints,↵    ", Date: "June 9, 2015"},
{PatNumber: "8,977,128", Title: "Encoding of wavelength converter systems,↵    ", Date: "March 10, 2015"},
{PatNumber: "8,929,733", Title: "Open shortest path first extensions↵        in support of wavelength switched optical networks,↵    ", Date: "January 6, 2015"},
{PatNumber: "8,923,695", Title: "Path computation element protocol↵        (PCEP) o…signment, and↵        impairment validation,↵    ", Date: "December 30, 2014"},
{PatNumber: "8,891,382", Title: " Impairment aware path computation↵        element method and system,↵    ", Date: "November 18, 2014"},
{PatNumber: "8,774,626", Title: "Distributed wavelength conversion↵        control for signaling protocols,↵    ", Date: "July 8, 2014"},
{PatNumber: "8,718,469", Title: "System and method for↵                impairment-a…ent in wavelength switched optical networks,↵    ", Date: "May 6, 2014"},
{PatNumber: "8,666,246", Title: "Path computation element↵                 method t…ent in wavelength switched optical networks,↵    ", Date: "March 4, 2014"},
{PatNumber: "8,655,173", Title: " Extending routing protocols to↵         accommodate wavelength switched optical networks,↵    ", Date: "February 18, 2014"},
{PatNumber: "8,630,543", Title: " Port wavelength restriction↵         encoding in wavelength switched optical network,↵    ", Date: "January 14, 2014"},
{PatNumber: "8,630,542", Title: "Distributing wavelength↵         compatible with signaling protocols,↵    ", Date: "January 14, 2014"},
{PatNumber: "8,532,484", Title: " Method for routing and↵         wavelength assign…ng for wavelength switched optical networks,↵    ", Date: "September 10, 2013"},
{PatNumber: "8,467,681", Title: "Method for characterizing wavelength↵         swit… generalized multi-protocol label switching,↵    ", Date: "June 18, 2013"},
{PatNumber: "8,452,175", Title: "Method for generalized multi-protocol label switch…d network element compatibility constraints,↵    ", Date: "May 28, 2013"},
{PatNumber: "8,442,399", Title: " Port wavelength restriction encoding in wavelength switched optical network,↵    ", Date: "May 14, 2013"},
{PatNumber: "8,396,364", Title: "System and method for impairment-aware routing and…signment in wavelength switched optical networks,", Date: "March 12, 2013"},
{PatNumber: "8,385,739", Title: "Encoding of wavelength converter systems,", Date: "February 26, 2013"},
{PatNumber: "8,374,502", Title: "Open shortest path first extensions in support of↵        wavelength switched optical networks,", Date: "February 12, 2013"},
{PatNumber: "8,358,662", Title: "Creating and maintaining traffic engineered database for↵        path computation element,", Date: "January 22, 2013"},
{PatNumber: "8,346,079", Title: "Path computation element protocol (PCEP) operation…wavelength assignment, and impairment validation,", Date: "January 1, 2013 "},
{PatNumber: "8,290,366", Title: "Extending path computation element protocol to↵   …signment in wavelength switched optical networks,", Date: "October 16, 2012 "},
{PatNumber: "8,249,451", Title: "Methods for characterizing optical switches and↵        multiplexers/demultiplexers,", Date: "August 21, 2012"},
{PatNumber: "8,238,749", Title: "Distributing wavelength compatible with signaling↵        protocols,", Date: "August 7, 2012"},
{PatNumber: "8,208,808", Title: "Distributed wavelength assignment using signaling↵…rotocols in wavelength switched optical networks,", Date: "June 26, 2012"},
{PatNumber: "8,208,405", Title: "Information encoding for impaired optical path↵        validation,", Date: "June 26, 2012"},
{PatNumber: "8,200,084", Title: "Encoding for information needed for routing and↵  …signment in wavelength switched optical networks,", Date: "June 12, 2012"},
{PatNumber: "8,145,056", Title: "Distributed wavelength conversion control for signaling↵        protocols,", Date: "March 27, 2012"},
{PatNumber: "8,059,960", Title: "Path computation element method to support routing…signment in wavelength switched optical networks,", Date: "November 15, 2011"},
{PatNumber: "7,054,554", Title: "Method and system for detecting network elements in an↵        optical communications network,", Date: "May 30, 2006"},
{PatNumber: "6,954,461", Title: "Communications network,", Date: "October 11, 2005"},
{PatNumber: "6,885,661", Title: "Private branch exchange built using an ATM Network,", Date: "April 26, 2005"},
{PatNumber: "6,807,174", Title: "Method and apparatus for transporting DS-X signals↵        through a packet network,", Date: "October 19, 2004"},
{PatNumber: "6,597,662", Title: "Apparatus and method for optimizing max-min fair rate↵        control in ABR sessions,", Date: "July 22, 2003"},
{PatNumber: "6,404,765", Title: "Method and apparatus for transporting DS-X signals↵        through a packet network,", Date: "June 11, 2002"},
{PatNumber: "6,370,114", Title: "Apparatus and method for optimizing congestion con…↵        information in a multi-protocol network,", Date: "April 9, 2002"},
{PatNumber: "6,128,301", Title: "Architecture for distribution of voice over ATM networks↵        ,", Date: "October 3, 2000"},
{PatNumber: "5,999,529", Title: "Method and apparatus for interworking ATM adaptation↵        layer formats,", Date: "December 7, 1999"},
{PatNumber: "5,912,880", Title: "System and method for ATM CBR timing recovery,", Date: "June 15, 1999"},
{PatNumber: "5,007,087", Title: "Method and apparatus for generating secure random↵        numbers using chaos,", Date: "April 9, 1991"}


];

